// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "radarlivre_api_observation-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy


#include <odb/pgsql/traits.hxx>
#include <odb/pgsql/database.hxx>
#include <odb/pgsql/transaction.hxx>
#include <odb/pgsql/connection.hxx>
#include <odb/pgsql/statement.hxx>
#include <odb/pgsql/statement-cache.hxx>
#include <odb/pgsql/simple-object-statements.hxx>
#include <odb/pgsql/container-statements.hxx>
#include <odb/pgsql/exceptions.hxx>
#include <odb/pgsql/simple-object-result.hxx>

namespace odb
{
  // radarlivre_api_observation
  //

  const char access::object_traits_impl< ::radarlivre_api_observation, id_pgsql >::
  persist_statement_name[] = "persist_radarlivre_api_observation";

  const char access::object_traits_impl< ::radarlivre_api_observation, id_pgsql >::
  find_statement_name[] = "find_radarlivre_api_observation";

  const char access::object_traits_impl< ::radarlivre_api_observation, id_pgsql >::
  update_statement_name[] = "update_radarlivre_api_observation";

  const char access::object_traits_impl< ::radarlivre_api_observation, id_pgsql >::
  erase_statement_name[] = "erase_radarlivre_api_observation";

  const char access::object_traits_impl< ::radarlivre_api_observation, id_pgsql >::
  query_statement_name[] = "query_radarlivre_api_observation";

  const char access::object_traits_impl< ::radarlivre_api_observation, id_pgsql >::
  erase_query_statement_name[] = "erase_query_radarlivre_api_observation";

  const unsigned int access::object_traits_impl< ::radarlivre_api_observation, id_pgsql >::
  persist_statement_types[] =
  {
    pgsql::int8_oid,
    pgsql::int8_oid,
    pgsql::numeric_oid,
    pgsql::numeric_oid,
    pgsql::numeric_oid,
    pgsql::numeric_oid,
    pgsql::numeric_oid,
    pgsql::numeric_oid,
    pgsql::int8_oid
  };

  const unsigned int access::object_traits_impl< ::radarlivre_api_observation, id_pgsql >::
  find_statement_types[] =
  {
    pgsql::int8_oid
  };

  const unsigned int access::object_traits_impl< ::radarlivre_api_observation, id_pgsql >::
  update_statement_types[] =
  {
    pgsql::int8_oid,
    pgsql::numeric_oid,
    pgsql::numeric_oid,
    pgsql::numeric_oid,
    pgsql::numeric_oid,
    pgsql::numeric_oid,
    pgsql::numeric_oid,
    pgsql::int8_oid,
    pgsql::int8_oid
  };

  struct access::object_traits_impl< ::radarlivre_api_observation, id_pgsql >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      pgsql::connection&,
      image_type&,
      id_image_type&,
      pgsql::binding&,
      pgsql::binding&,
      pgsql::native_binding&,
      const unsigned int*)
    {
    }
  };

  access::object_traits_impl< ::radarlivre_api_observation, id_pgsql >::id_type
  access::object_traits_impl< ::radarlivre_api_observation, id_pgsql >::
  id (const image_type& i)
  {
    pgsql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      pgsql::value_traits<
          long unsigned int,
          pgsql::id_bigint >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::radarlivre_api_observation, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // id
    //
    t[0UL] = 0;

    // flight_id
    //
    t[1UL] = 0;

    // latitude
    //
    if (t[2UL])
    {
      i.latitude_value.capacity (i.latitude_size);
      grew = true;
    }

    // longitude
    //
    if (t[3UL])
    {
      i.longitude_value.capacity (i.longitude_size);
      grew = true;
    }

    // altitude
    //
    if (t[4UL])
    {
      i.altitude_value.capacity (i.altitude_size);
      grew = true;
    }

    // verticalVelocity
    //
    if (t[5UL])
    {
      i.verticalVelocity_value.capacity (i.verticalVelocity_size);
      grew = true;
    }

    // horizontalVelocity
    //
    if (t[6UL])
    {
      i.horizontalVelocity_value.capacity (i.horizontalVelocity_size);
      grew = true;
    }

    // groundTrackHeading
    //
    if (t[7UL])
    {
      i.groundTrackHeading_value.capacity (i.groundTrackHeading_size);
      grew = true;
    }

    // timestamp
    //
    t[8UL] = 0;

    return grew;
  }

  void access::object_traits_impl< ::radarlivre_api_observation, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    std::size_t n (0);

    // id
    //
    if (sk != statement_update)
    {
      b[n].type = pgsql::bind::bigint;
      b[n].buffer = &i.id_value;
      b[n].is_null = &i.id_null;
      n++;
    }

    // flight_id
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.flight_id_value;
    b[n].is_null = &i.flight_id_null;
    n++;

    // latitude
    //
    b[n].type = pgsql::bind::numeric;
    b[n].buffer = i.latitude_value.data ();
    b[n].capacity = i.latitude_value.capacity ();
    b[n].size = &i.latitude_size;
    b[n].is_null = &i.latitude_null;
    n++;

    // longitude
    //
    b[n].type = pgsql::bind::numeric;
    b[n].buffer = i.longitude_value.data ();
    b[n].capacity = i.longitude_value.capacity ();
    b[n].size = &i.longitude_size;
    b[n].is_null = &i.longitude_null;
    n++;

    // altitude
    //
    b[n].type = pgsql::bind::numeric;
    b[n].buffer = i.altitude_value.data ();
    b[n].capacity = i.altitude_value.capacity ();
    b[n].size = &i.altitude_size;
    b[n].is_null = &i.altitude_null;
    n++;

    // verticalVelocity
    //
    b[n].type = pgsql::bind::numeric;
    b[n].buffer = i.verticalVelocity_value.data ();
    b[n].capacity = i.verticalVelocity_value.capacity ();
    b[n].size = &i.verticalVelocity_size;
    b[n].is_null = &i.verticalVelocity_null;
    n++;

    // horizontalVelocity
    //
    b[n].type = pgsql::bind::numeric;
    b[n].buffer = i.horizontalVelocity_value.data ();
    b[n].capacity = i.horizontalVelocity_value.capacity ();
    b[n].size = &i.horizontalVelocity_size;
    b[n].is_null = &i.horizontalVelocity_null;
    n++;

    // groundTrackHeading
    //
    b[n].type = pgsql::bind::numeric;
    b[n].buffer = i.groundTrackHeading_value.data ();
    b[n].capacity = i.groundTrackHeading_value.capacity ();
    b[n].size = &i.groundTrackHeading_size;
    b[n].is_null = &i.groundTrackHeading_null;
    n++;

    // timestamp
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.timestamp_value;
    b[n].is_null = &i.timestamp_null;
    n++;
  }

  void access::object_traits_impl< ::radarlivre_api_observation, id_pgsql >::
  bind (pgsql::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::radarlivre_api_observation, id_pgsql >::
  init (image_type& i,
        const object_type& o,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    bool grew (false);

    // id
    //
    if (sk == statement_insert)
    {
      long unsigned int const& v =
        o.id;

      bool is_null (false);
      pgsql::value_traits<
          long unsigned int,
          pgsql::id_bigint >::set_image (
        i.id_value, is_null, v);
      i.id_null = is_null;
    }

    // flight_id
    //
    {
      long unsigned int const& v =
        o.flight_id;

      bool is_null (false);
      pgsql::value_traits<
          long unsigned int,
          pgsql::id_bigint >::set_image (
        i.flight_id_value, is_null, v);
      i.flight_id_null = is_null;
    }

    // latitude
    //
    {
      double const& v =
        o.latitude;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.latitude_value.capacity ());
      pgsql::value_traits<
          double,
          pgsql::id_numeric >::set_image (
        i.latitude_value,
        size,
        is_null,
        v);
      i.latitude_null = is_null;
      i.latitude_size = size;
      grew = grew || (cap != i.latitude_value.capacity ());
    }

    // longitude
    //
    {
      double const& v =
        o.longitude;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.longitude_value.capacity ());
      pgsql::value_traits<
          double,
          pgsql::id_numeric >::set_image (
        i.longitude_value,
        size,
        is_null,
        v);
      i.longitude_null = is_null;
      i.longitude_size = size;
      grew = grew || (cap != i.longitude_value.capacity ());
    }

    // altitude
    //
    {
      double const& v =
        o.altitude;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.altitude_value.capacity ());
      pgsql::value_traits<
          double,
          pgsql::id_numeric >::set_image (
        i.altitude_value,
        size,
        is_null,
        v);
      i.altitude_null = is_null;
      i.altitude_size = size;
      grew = grew || (cap != i.altitude_value.capacity ());
    }

    // verticalVelocity
    //
    {
      double const& v =
        o.verticalVelocity;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.verticalVelocity_value.capacity ());
      pgsql::value_traits<
          double,
          pgsql::id_numeric >::set_image (
        i.verticalVelocity_value,
        size,
        is_null,
        v);
      i.verticalVelocity_null = is_null;
      i.verticalVelocity_size = size;
      grew = grew || (cap != i.verticalVelocity_value.capacity ());
    }

    // horizontalVelocity
    //
    {
      double const& v =
        o.horizontalVelocity;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.horizontalVelocity_value.capacity ());
      pgsql::value_traits<
          double,
          pgsql::id_numeric >::set_image (
        i.horizontalVelocity_value,
        size,
        is_null,
        v);
      i.horizontalVelocity_null = is_null;
      i.horizontalVelocity_size = size;
      grew = grew || (cap != i.horizontalVelocity_value.capacity ());
    }

    // groundTrackHeading
    //
    {
      double const& v =
        o.groundTrackHeading;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.groundTrackHeading_value.capacity ());
      pgsql::value_traits<
          double,
          pgsql::id_numeric >::set_image (
        i.groundTrackHeading_value,
        size,
        is_null,
        v);
      i.groundTrackHeading_null = is_null;
      i.groundTrackHeading_size = size;
      grew = grew || (cap != i.groundTrackHeading_value.capacity ());
    }

    // timestamp
    //
    {
      long unsigned int const& v =
        o.timestamp;

      bool is_null (false);
      pgsql::value_traits<
          long unsigned int,
          pgsql::id_bigint >::set_image (
        i.timestamp_value, is_null, v);
      i.timestamp_null = is_null;
    }

    return grew;
  }

  void access::object_traits_impl< ::radarlivre_api_observation, id_pgsql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // id
    //
    {
      long unsigned int& v =
        o.id;

      pgsql::value_traits<
          long unsigned int,
          pgsql::id_bigint >::set_value (
        v,
        i.id_value,
        i.id_null);
    }

    // flight_id
    //
    {
      long unsigned int& v =
        o.flight_id;

      pgsql::value_traits<
          long unsigned int,
          pgsql::id_bigint >::set_value (
        v,
        i.flight_id_value,
        i.flight_id_null);
    }

    // latitude
    //
    {
      double& v =
        o.latitude;

      pgsql::value_traits<
          double,
          pgsql::id_numeric >::set_value (
        v,
        i.latitude_value,
        i.latitude_size,
        i.latitude_null);
    }

    // longitude
    //
    {
      double& v =
        o.longitude;

      pgsql::value_traits<
          double,
          pgsql::id_numeric >::set_value (
        v,
        i.longitude_value,
        i.longitude_size,
        i.longitude_null);
    }

    // altitude
    //
    {
      double& v =
        o.altitude;

      pgsql::value_traits<
          double,
          pgsql::id_numeric >::set_value (
        v,
        i.altitude_value,
        i.altitude_size,
        i.altitude_null);
    }

    // verticalVelocity
    //
    {
      double& v =
        o.verticalVelocity;

      pgsql::value_traits<
          double,
          pgsql::id_numeric >::set_value (
        v,
        i.verticalVelocity_value,
        i.verticalVelocity_size,
        i.verticalVelocity_null);
    }

    // horizontalVelocity
    //
    {
      double& v =
        o.horizontalVelocity;

      pgsql::value_traits<
          double,
          pgsql::id_numeric >::set_value (
        v,
        i.horizontalVelocity_value,
        i.horizontalVelocity_size,
        i.horizontalVelocity_null);
    }

    // groundTrackHeading
    //
    {
      double& v =
        o.groundTrackHeading;

      pgsql::value_traits<
          double,
          pgsql::id_numeric >::set_value (
        v,
        i.groundTrackHeading_value,
        i.groundTrackHeading_size,
        i.groundTrackHeading_null);
    }

    // timestamp
    //
    {
      long unsigned int& v =
        o.timestamp;

      pgsql::value_traits<
          long unsigned int,
          pgsql::id_bigint >::set_value (
        v,
        i.timestamp_value,
        i.timestamp_null);
    }
  }

  void access::object_traits_impl< ::radarlivre_api_observation, id_pgsql >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      pgsql::value_traits<
          long unsigned int,
          pgsql::id_bigint >::set_image (
        i.id_value, is_null, id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::radarlivre_api_observation, id_pgsql >::persist_statement[] =
  "INSERT INTO \"radarlivre_api_observation\" "
  "(\"id\", "
  "\"flight_id\", "
  "\"latitude\", "
  "\"longitude\", "
  "\"altitude\", "
  "\"verticalVelocity\", "
  "\"horizontalVelocity\", "
  "\"groundTrackHeading\", "
  "\"timestamp\") "
  "VALUES "
  "($1, $2, $3, $4, $5, $6, $7, $8, $9)";

  const char access::object_traits_impl< ::radarlivre_api_observation, id_pgsql >::find_statement[] =
  "SELECT "
  "\"radarlivre_api_observation\".\"id\", "
  "\"radarlivre_api_observation\".\"flight_id\", "
  "\"radarlivre_api_observation\".\"latitude\", "
  "\"radarlivre_api_observation\".\"longitude\", "
  "\"radarlivre_api_observation\".\"altitude\", "
  "\"radarlivre_api_observation\".\"verticalVelocity\", "
  "\"radarlivre_api_observation\".\"horizontalVelocity\", "
  "\"radarlivre_api_observation\".\"groundTrackHeading\", "
  "\"radarlivre_api_observation\".\"timestamp\" "
  "FROM \"radarlivre_api_observation\" "
  "WHERE \"radarlivre_api_observation\".\"id\"=$1";

  const char access::object_traits_impl< ::radarlivre_api_observation, id_pgsql >::update_statement[] =
  "UPDATE \"radarlivre_api_observation\" "
  "SET "
  "\"flight_id\"=$1, "
  "\"latitude\"=$2, "
  "\"longitude\"=$3, "
  "\"altitude\"=$4, "
  "\"verticalVelocity\"=$5, "
  "\"horizontalVelocity\"=$6, "
  "\"groundTrackHeading\"=$7, "
  "\"timestamp\"=$8 "
  "WHERE \"id\"=$9";

  const char access::object_traits_impl< ::radarlivre_api_observation, id_pgsql >::erase_statement[] =
  "DELETE FROM \"radarlivre_api_observation\" "
  "WHERE \"id\"=$1";

  const char access::object_traits_impl< ::radarlivre_api_observation, id_pgsql >::query_statement[] =
  "SELECT "
  "\"radarlivre_api_observation\".\"id\", "
  "\"radarlivre_api_observation\".\"flight_id\", "
  "\"radarlivre_api_observation\".\"latitude\", "
  "\"radarlivre_api_observation\".\"longitude\", "
  "\"radarlivre_api_observation\".\"altitude\", "
  "\"radarlivre_api_observation\".\"verticalVelocity\", "
  "\"radarlivre_api_observation\".\"horizontalVelocity\", "
  "\"radarlivre_api_observation\".\"groundTrackHeading\", "
  "\"radarlivre_api_observation\".\"timestamp\" "
  "FROM \"radarlivre_api_observation\"";

  const char access::object_traits_impl< ::radarlivre_api_observation, id_pgsql >::erase_query_statement[] =
  "DELETE FROM \"radarlivre_api_observation\"";

  const char access::object_traits_impl< ::radarlivre_api_observation, id_pgsql >::table_name[] =
  "\"radarlivre_api_observation\"";

  void access::object_traits_impl< ::radarlivre_api_observation, id_pgsql >::
  persist (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              obj,
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    callback (db,
              obj,
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::radarlivre_api_observation, id_pgsql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace pgsql;
    using pgsql::update_statement;

    callback (db, obj, callback_event::pre_update);

    pgsql::transaction& tr (pgsql::transaction::current ());
    pgsql::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj.id);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::radarlivre_api_observation, id_pgsql >::
  erase (database& db, const id_type& id)
  {
    using namespace pgsql;

    ODB_POTENTIALLY_UNUSED (db);

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::radarlivre_api_observation, id_pgsql >::pointer_type
  access::object_traits_impl< ::radarlivre_api_observation, id_pgsql >::
  find (database& db, const id_type& id)
  {
    using namespace pgsql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::radarlivre_api_observation, id_pgsql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::radarlivre_api_observation, id_pgsql >::
  reload (database& db, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj.id);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::radarlivre_api_observation, id_pgsql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace pgsql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::radarlivre_api_observation, id_pgsql >::object_type >
  access::object_traits_impl< ::radarlivre_api_observation, id_pgsql >::
  query (database&, const query_base_type& q)
  {
    using namespace pgsql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        sts.connection (),
        query_statement_name,
        text,
        false,
        true,
        q.parameter_types (),
        q.parameter_count (),
        q.parameters_binding (),
        imb));

    st->execute ();
    st->deallocate ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) pgsql::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::radarlivre_api_observation, id_pgsql >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      erase_query_statement_name,
      text,
      q.parameter_types (),
      q.parameter_count (),
      q.parameters_binding ());

    return st.execute ();
  }
}

#include <odb/post.hxx>
